[package]
name = "building-blocks"
version = "0.3.0"
edition = "2018"
authors = ["Duncan <bonsairobo@gmail.com>"]
description = "Data types, collections, and algorithms for working with maps on 2D and 3D integer lattices. Commonly known as voxel data."
license = "MIT"
repository = "https://github.com/bonsairobo/building-blocks"
keywords = ["voxel"]

[package.metadata.docs.rs]
features = ["glam", "image", "lz4", "mesh", "mint", "nalgebra", "ncollide", "procgen", "search", "vox"]

[features]
default = ["lz4", "mesh", "procgen", "search"]

# Optional crates.
image = ["building_blocks_image"]
mesh = ["building_blocks_mesh"]
procgen = ["building_blocks_procgen"]
search = ["building_blocks_search"]
vox = ["building_blocks_vox"]

# Math type conversions.
glam = ["building_blocks_core/glam"]
mint = ["building_blocks_core/mint"]
nalgebra = ["building_blocks_core/nalgebra"]

# Compression backends.
lz4 = ["building_blocks_storage/lz4"]
snappy = ["building_blocks_storage/snap"]

# Collisions with `OctreeSet` and `OctreeDBVT`.
ncollide = ["building_blocks_search/ncollide"]

[workspace]
members = ["crates/*"]
exclude = ["benches"]

[profile.dev]
opt-level = 2

[profile.release]
lto = true

[profile.bench]
lto = true

[dependencies]
building_blocks_core = { path = "crates/building_blocks_core", version = "0.3" }
building_blocks_storage = { path = "crates/building_blocks_storage", version = "0.3" }

# Optional, feature-gated
building_blocks_image = { path = "crates/building_blocks_image", version = "0.3", optional = true }
building_blocks_mesh = { path = "crates/building_blocks_mesh", version = "0.3", optional = true }
building_blocks_procgen = { path = "crates/building_blocks_procgen", version = "0.3", optional = true }
building_blocks_search = { path = "crates/building_blocks_search", version = "0.3", optional = true }
building_blocks_vox = { path = "crates/building_blocks_vox", version = "0.3", optional = true }

[dev-dependencies]
bevy = "0.3" # for examples
log = "0.4"

[[bin]]
name = "measure_compression_rate"
required-features = ["lz4", "snappy", "vox"]

[[example]]
name = "bevy_meshing"
path = "examples/bevy_meshing/bevy_meshing.rs"
required-features = ["mesh"]
