[package]
name = "building-blocks"
version = "0.1.0"
authors = ["Duncan <bonsairobo@gmail.com>"]
edition = "2018"

description = "Data types, collections, and algorithms for working with maps on 2D and 3D integer lattices. Commonly known as voxel data."

[features]
default = ["mesh", "procgen", "search"]

image = ["building_blocks_image"]
mesh = ["building_blocks_mesh"]
nalg = ["building_blocks_core/nalg"]
partition = ["building_blocks_partition"]
procgen = ["building_blocks_procgen"]
search = ["building_blocks_search"]
vox = ["building_blocks_vox"]

[workspace]
members = ["crates/*"]
exclude = ["benches"]

[dependencies]
building_blocks_core = { path = "crates/building_blocks_core", version = "0.1" }
building_blocks_storage = { path = "crates/building_blocks_storage", version = "0.1" }

# Optional, feature-gated
building_blocks_image = { path = "crates/building_blocks_image", version = "0.1", optional = true }
building_blocks_mesh = { path = "crates/building_blocks_mesh", version = "0.1", optional = true }
building_blocks_partition = { path = "crates/building_blocks_partition", version = "0.1", optional = true }
building_blocks_procgen = { path = "crates/building_blocks_procgen", version = "0.1", optional = true }
building_blocks_search = { path = "crates/building_blocks_search", version = "0.1", optional = true }
building_blocks_vox = { path = "crates/building_blocks_vox", version = "0.1", optional = true }

[dev-dependencies]
bevy = "0.2" # for examples
log = "0.4"

[[example]]
name = "bevy_meshing"
path = "examples/bevy_meshing/bevy_meshing.rs"
