[package]
name = "building_blocks_storage"
version = "0.2.0"
edition = "2018"
authors = ["Duncan <bonsairobo@gmail.com>"]
license = "MIT"
repository = "https://github.com/bonsairobo/building-blocks"
keywords = ["voxel"]

description = "Efficient storage for maps on sparse or dense, 2D and 3D integer lattices."

[dependencies]
either = "1.6"
fnv = "1.0"
futures = "0.3"
itertools = "0.9"
lz4 = "1.23"
num = "0.3"
serde = { version = "1.0", features = ["derive"] }

building_blocks_core = { path = "../building_blocks_core", version = "0.2" }

compressible-map = { version = "0.1", features = ["bincode_lz4"] }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "accessors"
harness = false

[[bench]]
name = "compression"
harness = false
