[package]
name = "building_blocks_storage"
version = "0.2.1"
edition = "2018"
authors = ["Duncan <bonsairobo@gmail.com>"]
license = "MIT"
repository = "https://github.com/bonsairobo/building-blocks"
keywords = ["voxel", "mesh"]

description = "Efficient storage for maps on sparse or dense, 2D and 3D integer lattices."

[features]
snappy = ["compressible-map/snap"]

[dependencies]
either = "1.6"
fnv = "1.0"
futures = "0.3"
itertools = "0.9"
num = "0.3"
serde = { version = "1.0", features = ["derive"] }

building_blocks_core = { path = "../building_blocks_core", version = "0.2" }

compressible-map = { version = "0.2", features = ["compressed-bincode", "lz4"] }

[dev-dependencies]
criterion = "0.3"
rand = "0.7"

[[bench]]
name = "accessors"
harness = false

[[bench]]
name = "compression"
harness = false

[[bench]]
name = "octree"
harness = false
