[package]
name = "building_blocks_search"
version = "0.1.0"
authors = ["Duncan <bonsairobo@gmail.com>"]
edition = "2018"

[dependencies]
indexmap = "1.5"
itertools = "0.9"

building_blocks_core = { path = "../building_blocks_core", version = "0.1" }
building_blocks_storage = { path = "../building_blocks_storage", version = "0.1" }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "find_surface"
harness = false
