name: Rust Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Lint
      run: cargo clippy --all --all-features
    - name: Build
      run: cargo build --verbose --all --all-features
    - name: Run tests
      run: cargo test --verbose --all --all-features
