name: Build and Test

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.rs'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.rs'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get Latest Stable Rust
      uses: actions-rs/toolchain@v1
      with:
        default: true
        components: clippy
    - name: Get SDL2
      run: sudo apt-get update && sudo apt-get install libsdl2-dev
    - name: Lint
      run: cargo clippy --all --all-features
    - name: Build
      run: cargo build --verbose --all --all-features && cargo bench --all --no-run
    - name: Run tests
      run: cargo test --verbose --all --all-features
